DROP TABLE USUARIO

CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(250) NOT NULL
);

CREATE TABLE VIDEOS(
    id_videos NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    id_canal NUMBER REFERENCES CANAL(id_canal),
    id_comentarios NUMBER REFERENCES COMENTARIOS(id_comentarios)
);

CREATE TABLE PUBLICACION(
    id_publicacion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(100) NOT NULL,
    id_canal NUMBER REFERENCES CANAL(id_canal),
    id_comentarios NUMBER REFERENCES COMENTARIOS(id_comentarios)
);  

CREATE TABLE SUSCRIPCIONES(
    id_suspcripcines NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_canal NUMBER REFERENCES CANAL(id_canal),
    id_usuario NUMBER REFERENCES USUARIO(id_usuario)
);

CREATE TABLE CANAL(
    id_canal NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE COMENTARIOS(
    id_comentarios NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIO(id_usuario),
    comentario VARCHAR2(100)
);


INSERT INTO CANAL(NOMBRE) VALUES('31 Minutos');
INSERT INTO CANAL(NOMBRE) VALUES('JuegaGerman');
INSERT INTO CANAL(NOMBRE) VALUES('Fernanfloo');
INSERT INTO CANAL(NOMBRE) VALUES('Rubius');

INSERT INTO USUARIO(nombre, correo) VALUES('Jairo', 'jairo.pineda@gmail.com');

INSERT INTO VIDEOS(TITULO) VALUES('Yo nunca vi televisión porque es muy fome');
INSERT INTO VIDEOS(TITULO) VALUES('Pase 24 horas conectado al Apple Vision Pro');
INSERT INTO VIDEOS(TITULO) VALUES('Five night at freddy NOCHE 5');
INSERT INTO VIDEOS(TITULO) VALUES('No juegues este juego a las 3:00 AM');