DROP TABLE VIDEO CASCADE CONSTRAINTS;
DROP TABLE TIPO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE CUENTA CASCADE CONSTRAINTS;
DROP TABLE SUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE CANAL CASCADE CONSTRAINTS;
DROP TABLE LISTA_REPRODUCCION CASCADE CONSTRAINTS;
DROP TABLE COMENTARIO CASCADE CONSTRAINTS;
DROP TABLE FACTURACION CASCADE CONSTRAINTS;

CREATE TABLE VIDEO (
    id_video NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_video VARCHAR2(200),
    descripcion VARCHAR2(200),
    me_gusta NUMBER,
    me_gusta_activo CHAR(1),
    comentario_activo CHAR(1),
    duracion_segundos NUMBER,
    fecha_publicacion DATE
);

CREATE TABLE TIPO(
    id_tipo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_tipo VARCHAR2(100)
);

CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR2(100),
    id_cuenta NUMBER REFERENCES CUENTA(id_cuenta)
);

CREATE TABLE CUENTA(
    id_cuenta NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR2(200),
    password VARCHAR2(14)
);

CREATE TABLE CANAL(
    id_canal NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_canal VARCHAR2(100),
    id_usuario NUMBER REFERENCES USUARIO(id_usuario)
);

CREATE TABLE LISTA_REPRODUCCION(
    id_lista NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_video NUMBER REFERENCES VIDEO(id_video)
);

SELECT * FROM VIDEO;
SELECT * FROM TIPO;
SELECT * FROM USUARIO;
SELECT * FROM CUENTA;
SELECT * FROM SUSCRIPCION;
SELECT * FROM CANAL;
SELECT * FROM LISTA_REPRODUCCION;
SELECT * FROM COMENTARIO;
SELECT * FROM FACTURACION;

COMMIT;