DROP TABLE CANCION_GENERO CASCADE CONSTRAINT;
DROP TABLE CANCION CASCADE CONSTRAINT;
DROP TABLE ARTISTA CASCADE CONSTRAINT;
DROP TABLE GENERO CASCADE CONSTRAINT;
DROP TABLE ALBUM CASCADE CONSTRAINT;
DROP TABLE PAIS CASCADE CONSTRAINT;



CREATE TABLE PAIS(
id_pais NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nombre VARCHAR2(100) NOT NULL
);
CREATE TABLE ALBUM(
    id_album NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    fecha_lanzamiento DATE 
);
CREATE TABLE GENERO(
    id_genero NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);
CREATE TABLE ARTISTA(
    id_artista NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    esta_verificado CHAR(1),
    id_pais NUMBER REFERENCES PAIS(id_pais)



);


CREATE TABLE CANCION(
    ID_cancion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    id_artista NUMBER REFERENCES ARTISTA(id_artista),
    id_album number REFERENCES ALBUM(id_album),
    duracion_segundos NUMBER NOT NULL,
    fecha_lanzamiento DATE
);


CREATE TABLE CANCION_GENERO(
    ID_cancion NUMBER REFERENCES CANCION(ID_cancion),
    id_genero NUMBER REFERENCES GENERO(id_genero)
);
--DROP TABLE CANCION;
INSERT INTO PAIS(nombre) VALUES('canada');
INSERT INTO ALBUM(nombre, fecha_lanzamiento) VALUES ('STARBOY', 2016-11-25 );

