DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE VIDEOS CASCADE CONSTRAINTS;
DROP TABLE REPRODUCCIONES CASCADE CONSTRAINTS;
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE DISLIKES CASCADE CONSTRAINTS;
DROP TABLE CANALES CASCADE CONSTRAINTS;
DROP TABLE COMENTARIOS CASCADE CONSTRAINT;
DROP TABLE NOTIFICACIONES CASCADE CONSTRAINT;

CREATE TABLE USUARIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    fecha_de_nacimiento DATE NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    contrasena VARCHAR2(100) NOT NULL
);


CREATE TABLE VIDEOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_video VARCHAR2(150) NOT NULL UNIQUE,
    duracion_segundos NUMBER NOT NULL,
    fecha_de_publicacion DATE,
    descripcion_video VARCHAR2(250),
    fecha_publicacion DATE NOT NULL,
    VIDEO_PUBLICO CHAR(1)
)

CREATE TABLE REPRODUCCIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIO(id),
    id_video NUMBER REFERENCES VIDEOS(id)
)

CREATE TABLE LIKES(
    id_video NUMBER REFERENCES VIDEOS(id),
    id_usuario NUMBER REFERENCES USUARIOS(id)
)

CREATE TABLE DISLIKES(
    id_video NUMBER REFERENCES VIDEOS(id),
    id_usuario NUMBER REFERENCES USUARIOS(id)
)


CREATE TABLE CANALES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    fecha_de_creacion DATE,
    id_usuario NUMBER REFERENCES USUARIOS(id),
    id_video NUMBER REFERENCES VIDEOS(id)
)

CREATE TABLE COMENTARIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIO(id),
    id_video NUMBER REFERENCES VIDEOS(id),
    COMENTARIO VARCHAR2(500) NOT NULL
)

CREATE TABLE NOTIFICACIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIOS(id),
    id_canales NUMBER REFERENCES CANALES(id),
    ACTIVA CHAR(1)
);

COMMIT;