CREATE TABLE TIPO_USUARIO (
    id_tipo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_tipo_usuario VARCHAR2(30)
);

CREATE TABLE USUARIOS (
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL,
    id_tipo NUMBER REFERENCES TIPO_USUARIO(id_tipo),
    esta_verificado CHAR(1),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_nacimiento DATE NOT NULL
);

CREATE TABLE TIPO_PUBLICACION (
    id_tipo_publicacion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_tipo_publicacion VARCHAR2(30)
);

CREATE TABLE PUBLICACION (
    id_publicacion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIOS(id_usuario),
    id_tipo_publicacion NUMBER REFERENCES TIPO_PUBLICACION(id_tipo_publicacion)
);

CREATE TABLE PAIS (
    id_pais NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30)
);

CREATE TABLE MENSAJERIA (
    id_mensajeria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE SEGUIDOR (
    id_seguidor NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_seguido TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE SEGUIDOR_USUARIO (
    id_usuario NUMBER REFERENCES USUARIOS(id_usuario),
    id_seguidor NUMBER REFERENCES SEGUIDOR(id_seguidor),
    fecha_seguido TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (id_usuario, id_seguidor)
);

CREATE TABLE ME_GUSTA (
    id_usuario NUMBER REFERENCES USUARIOS(id_usuario)
);

COMMIT;
