
CREATE TABLE TIPO_DE_PUBLICACION(
    id_tipo_de_publicacion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(40) NOT NULL
);

CREATE TABLE TIPO_DE_CHAT(
    id_tipo_de_chat NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(40) NOT NULL
);

CREATE TABLE TIPO_DE_USUARIO(
    id_tipo_de_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(80) NOT NULL
);



CREATE TABLE PAIS(
    id_pais NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE SEGUIDOR(
    id_seguidor NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_seguido TIMESTAMP DEFAULT SYSTIMESTAMP
);


CREATE TABLE CHATS(
    id_chat NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_tipo_de_usuario REFERENCES TIPO_DE_USUARIO(id_tipo_de_usuario),
    id_tipo_de_chat NUMBER REFERENCES TIPO_DE_CHAT(id_tipo_de_chat)

);

CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    esta_verificado CHAR(1),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_nacimiento DATE,
    id_pais NUMBER REFERENCES PAIS(id_pais),
    id_tipo_de_usuario NUMBER REFERENCES TIPO_DE_USUARIO(id_tipo_de_usuario)
);

CREATE TABLE SEGUIDOR_USUARIO(
    id_usuario REFERENCES USUARIO(id_usuario),
    id_seguidor REFERENCES SEGUIDOR(id_seguidor),
    fecha_seguido TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO TIPO_DE_PUBLICACION(tipo) VALUES ('HISTORIA');
INSERT INTO TIPO_DE_PUBLICACION(tipo) VALUES ('POST');
INSERT INTO TIPO_DE_PUBLICACION(tipo) VALUES ('REEL');
INSERT INTO TIPO_DE_PUBLICACION(tipo) VALUES ('NOTA');
INSERT INTO TIPO_DE_PUBLICACION(tipo) VALUES ('INSTANTANEA');
COMMIT;

INSERT INTO TIPO_DE_CHAT(tipo) VALUES ('GRUPAL');
INSERT INTO TIPO_DE_CHAT(tipo) VALUES ('PERSONAL');
COMMIT;

INSERT INTO TIPO_DE_USUARIO(tipo) VALUES ('PROFESIONAL');
INSERT INTO TIPO_DE_USUARIO(tipo) VALUES ('NORMAL');
COMMIT;

INSERT INTO PAIS(nombre) VALUES ('Chile');
INSERT INTO PAIS(nombre) VALUES ('Argentina');
INSERT INTO PAIS(nombre) VALUES ('Estados Unidos');
INSERT INTO PAIS(nombre) VALUES ('Inglaterra');
INSERT INTO PAIS(nombre) VALUES ('Alemania');
COMMIT;


