CREATE TABLE USUARIOS(
    id_usuarios NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    nombre VARCHAR2(30) not NULL UNIQUE,
    canal CHAR(1)
);

CREATE TABLE PUBLICACION(
    id_publicacion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    fecha_de_publicacion DATE,
    id_categorias NUMBER REFERENCES CATEGORIAS(id_categorias)
);

CREATE TABLE CANAL(
    id_canal NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20)
);

CREATE TABLE VIDEOS(
    id_video NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(30) NOT NULL,
    duracion_segundos NUMBER NOT NULL,
    descripcion VARCHAR2(100)
);

CREATE TABLE SHORTS(
    id_shorts NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(50) NOT NULL,
    duracion_segundos NUMBER NOT NULL,
    descripcion VARCHAR2(100)
);

CREATE TABLE DIRECTOS(
    id_directo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(30) NOT NULL,
    inicio_directo DATE
);

CREATE TABLE COMENTARIOS(
    id_comentarios NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    comentario VARCHAR2(200) NOT NULL,
    id_usuarios NUMBER REFERENCES USUARIOS(id_usuarios),
    id_publicacion NUMBER REFERENCES PUBLICACION(id_publicacion)
);

CREATE TABLE HASHTAGS(
    id_hashtag NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_hashtag VARCHAR2(20)
);

CREATE TABLE CATEGORIAS(
    id_categorias NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    categoria VARCHAR2(20) NOT NULL
);

