DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE CANAL CASCADE CONSTRAINTS;
DROP TABLE VIDEO CASCADE CONSTRAINTS;
DROP TABLE COMENTARIO CASCADE CONSTRAINTS;
DROP TABLE HASHTAG CASCADE CONSTRAINTS;
DROP TABLE HASHTAG_VIDEO CASCADE CONSTRAINTS;

CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE CANAL(
    id_canal NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    id_usuario NUMBER REFERENCES USUARIO(id_usuario)
);

CREATE TABLE VIDEO(
    id_video NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(250) NOT NULL,
    duracion NUMBER NOT NULL,
    descripcion VARCHAR2(250) NOT NULL,
    numero_reproducciones NUMBER,
    numero_likes NUMBER,
    numero_dislikes NUMBER,
    fecha_subida DATE NOT NULL,
    esta_monetizado CHAR(1) NOT NULL,
    comentarios_bloqueados CHAR(1) NOT NULL,

    id_canal NUMBER REFERENCES CANAL(id_canal)
);

CREATE TABLE COMENTARIO(
    id_comentario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    texto VARCHAR2(250) NOT NULL,
    numero_likes NUMBER,
    numero_dislikes NUMBER,
    fecha_escrito DATE NOT NULL,
    tiene_like_del_canal CHAR(1),

    id_respuesta NUMBER REFERENCES COMENTARIO(id_comentario),

    id_usuario NUMBER REFERENCES USUARIO(id_usuario),
    id_video NUMBER REFERENCES VIDEO(id_video)
);



CREATE TABLE HASHTAG(
    id_hashtag NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE HASHTAG_VIDEO(
    id_hashtag NUMBER REFERENCES HASHTAG(id_hashtag),

    id_video NUMBER REFERENCES VIDEO(id_video)
);

CREATE TABLE SUSCRIPCION(
    id_usuario NUMBER REFERENCES USUARIO(id_usuario),
    
    id_canal NUMBER REFERENCES CANAL(id_canal)
);

CREATE TABLE NOTIFICACION(
    id_notificacion NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    estado_notificacion VARCHAR2(30)
);



