CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    fecha_de_nacimiento VARCHAR2(100) NOT NULL,
    Correo VARCHAR2 (100) NOT NULL,
    Constrasena VARCHAR2(100) NOT NULL
);
CREATE TABLE CANALES(
    id_canal NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_videos 
);


CREATE TABLE VIDEO(
    id_video NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_video VARCHAR2(100) NOT NULL ,
    fecha_lanzamiento DATE NOT NULL,
    id_like REFERENCES LIKE(id_like),
    id_dislike REFERENCES DISLIKES(id_dislike),
    Descripcion_video VARCHAR2(100)
);

CREATE TABLE REPRODUCCIONES(
    id_reproducciones NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id_usuario),
    id_video REFERENCES VIDEO(id_video)
);

CREATE TABLE LIKE(
    id_like NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id_usuario)

);

CREATE TABLE DISLIKE(
    id_dislike NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id_usuario)
);

CREATE TABLE COMENTARIOS(
    id_comentarios NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id_usuario),
    id_video REFERENCES VIDEO(id_video)

);
COMMIT;