CREATE TABLE USUARIO(
    PK_ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE
);
CREATE TABLE USUARIO_CUENTA(
    PK_ID_USU_CUENTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL
);
CREATE TABLE CANAL(
    PK_ID_CANAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_CANAL VARCHAR2(100),
    DESCRIPCION VARCHAR2(250)
);
CREATE TABLE VIDEOS(
    PK_ID_VIDEOS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CATEGORIA_VIDEO REFERENCES CATEGORIAS_VIDEOS(PK_ID_CATEGORIA),
    titulo VARCHAR2(100),
    DESCRIPCION VARCHAR2(100),
    FECHA_PUBLICACION DATE,
    DURACION_SEGUNDOS NUMBER
);
CREATE TABLE COMENTARIOS(
    PK_ID_COMENTARIOS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER REFERENCES USUARIO(PK_ID_USUARIO)
);
CREATE TABLE PAIS_ORIGEN(
    PK_PAIS_PRIGEN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_PAIS VARCHAR2(100)
);
CREATE TABLE CATEGORIAS_VIDEOS(
    PK_ID_CATEGORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL UNIQUE
);