DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE PERFIL CASCADE CONSTRAINTS;
DROP TABLE FOTO CASCADE CONSTRAINTS;
DROP TABLE PREFERENCIA CASCADE CONSTRAINTS;
DROP TABLE EMPAREJAMIENTO CASCADE CONSTRAINTS;
DROP TABLE ME_GUSTA CASCADE CONSTRAINTS;
DROP TABLE MENSAJE CASCADE CONSTRAINTS;





CREATE TABLE USUARIO (
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CORREO VARCHAR2(100),
    CONTRASENA VARCHAR2 (100),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE PERFIL(
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BIOGRAFIA VARCHAR2(250),
    GENERO CHAR(1),
    UBICACION VARCHAR2(100)
);

CREATE TABLE FOTO(
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    URL_FOTO VARCHAR2 (250),
    PRINCIPAL CHAR(1)

);

CREATE TABLE PREFERENCIA(
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GENERO_PREFERIO VARCHAR2(30),
    EDAD_MINIMA NUMERIC,
    EDAD_MAXIMA NUMERIC,
    DISTANCIA_MAXIMA NUMERIC
);

CREATE TABLE EMPAREJAMIENTO(
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO1 NUMERIC,
    USUARIO2 NUMERIC,
    FECHA_MATCH DATE
);


CREATE TABLE ME_GUSTA (
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ORIGEN NUMERIC,
    USUARIO_DESTINO NUMERIC
);


CREATE TABLE MENSAJE(
    ID  NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONTENIDO VARCHAR(500),
    FECHA_ENVIO DATE
);