DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE PERFIL CASCADE CONSTRAINTS;
DROP TABLE FOTO CASCADE CONSTRAINTS;
DROP TABLE PREFERENCIA CASCADE CONSTRAINTS;
DROP TABLE EMPAREJAMIENTO CASCADE CONSTRAINTS;
DROP TABLE ME_GUSTA CASCADE CONSTRAINTS;
DROP TABLE MENSAJE CASCADE CONSTRAINTS;





CREATE TABLE USUARIO (
    ID_USUSARIO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    CONTRASENA VARCHAR2 (100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    PRIMARY KEY (ID_USUSARIO)

);

CREATE TABLE PERFIL (
    ID_PERFIL NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMERIC NOT NULL,
    BIOGRAFIA VARCHAR2(250),
    GENERO CHAR(1),
    UBICACION VARCHAR2(100),
    CONSTRAINT fk_perfil_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE FOTO (
    ID_FOTO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMERIC NOT NULL,
    URL_FOTO VARCHAR2(250) NOT NULL,
    PRINCIPAL CHAR(1),
    CONSTRAINT fk_foto_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PREFERENCIA (
    ID_PREFERENCIA NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMERIC NOT NULL,
    GENERO_PREFERIO VARCHAR2(30),
    EDAD_MINIMA NUMERIC,
    EDAD_MAXIMA NUMERIC,
    DISTANCIA_MAXIMA NUMERIC,
    CONSTRAINT fk_preferencia_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE EMPAREJAMIENTO (
    ID_EMPAREJAMIENTO NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO1 NUMERIC NOT NULL,
    USUARIO2 NUMERIC NOT NULL,
    FECHA_MATCH DATE NOT NULL,
    CONSTRAINT fk_emp_usuario1 FOREIGN KEY (USUARIO1) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT fk_emp_usuario2 FOREIGN KEY (USUARIO2) REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE ME_GUSTA (
    ID_ME_GUSTA NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ORIGEN NUMERIC NOT NULL,
    USUARIO_DESTINO NUMERIC NOT NULL,
    FECHA_ME_GUSTA DATE NOT NULL,
    CONSTRAINT fk_megusta_origen FOREIGN KEY (USUARIO_ORIGEN) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT fk_megusta_destino FOREIGN KEY (USUARIO_DESTINO) REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE MENSAJE (
    ID_MENSAJE NUMERIC GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMISOR NUMERIC NOT NULL,
    ID_EMPAREJAMIENTO NUMERIC NOT NULL,
    CONTENIDO VARCHAR2(500),
    FECHA_ENVIO DATE,
    CONSTRAINT fk_mensaje_emparejamiento FOREIGN KEY (ID_EMPAREJAMIENTO) REFERENCES EMPAREJAMIENTO(ID_EMPAREJAMIENTO),
    CONSTRAINT fk_mensaje_emisor FOREIGN KEY (ID_EMISOR) REFERENCES USUARIO(ID_USUARIO)
);