DROP TABLE USUARIO;
DROP TABLE FOTOS_PERFIL;
DROP TABLE PREFERENCIAS;
DROP TABLE LIKE;
DROP TABLE TIPO_INTERACCION;
DROP TABLE TIPO_GENERO;
DROP TABLE MATCHES;
DROP TABLE PAIS;
DROP TABLE REGION;
DROP TABLE COMUNA;
DROP TABLE CIUDAD;
DROP TABLE DIRECCION;


CREATE TABLE USUARIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    id_genero REFERENCES TIPO_GENERO(id),
    fecha_nacimiento DATE,
    id_direccion REFERENCES DIRECCION(id),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)


--UN USUARIO PUEDE TENER VARIAS FOTOS DE PERFIL, PERO CADA FOTO PERTENECE A UN ÚNICO USUARIO
CREATE TABLE FOTOS_PERFIL(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id),
    url VARCHAR2(100)
)

--CADA PERFIL DE USUARIO DISPONE DE UN CONJUNTO DE PREFERENCIAS, Y CADA CONUJUNTO DE PREFERENCIAS PERTENECE A UN ÚNICO USUARIO
CREATE TABLE PREFERENCIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_genero_interesado REFERENCES TIPO_GENERO(id),
    edad_minima NUMBER,
    edad_maxima NUMBER,
    distancia_maxkm NUMBER

)

CREATE TABLE LIKE(
    id NUMBER GENERATED ALWAYS  AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id),
    id_usuario_destino REFERENCES USUARIO(id),
    id_interaccion REFERENCES TIPO_INTERACCION(id)

)


CREATE TABLE TIPO_INTERACCION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
)
CREATE TABLE TIPO_GENERO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30)
)

--SE CREA CUANDO DOS USUARIOS SE DAN LIKE SIMULTANEAMENTE
CREATE TABLE MATCHES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario REFERENCES USUARIO(id),
    id_usuario2 REFERENCES USUARIO(id)

)

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
)

CREATE TABLE REGION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_pais REFERENCES PAIS(id),
    nombre VARCHAR2(50)
)

CREATE TABLE COMUNA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_region REFERENCES REGION(id),
    nombre VARCHAR2(50)
)

CREATE TABLE CIUDAD(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_comuna REFERENCES COMUNA(id),
    nombre VARCHAR2(50)
)

CREATE TABLE DIRECCION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_ciudad REFERENCES CIUDAD(id),
    nombre VARCHAR2(50)
)

COMMIT;