--videos
--CUENTA - usuarios -canales
--suscripcion comentarios lista de reproduccion miembros, facturacion, publicacion, membresia

DROP TABLE VIDEO CASCADE CONSTRAINTS;
DROP TABLE TIPO_VIDEO CASCADE CONSTRAINTS;
DROP TABLE CUENTA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE SUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE CANAL CASCADE CONSTRAINTS;
DROP TABLE COMENTARIO CASCADE CONSTRAINTS;
DROP TABLE LISTA_DE_REPRODUCCION CASCADE CONSTRAINTS;
DROP TABLE FACTURACION CASCADE CONSTRAINTS;

CREATE TABLE TIPO_VIDEO(
    id_tipo_video GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100)
);

CREATE TABLE VIDEO(
    id_video GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(200),
    me_gusta NUMBER,
    me_gusta_activados CHAR(1),
    comentarios_activados CHAR(1),
    id_tipo_video NUMBER REFERENCES TIPO_VIDEO(id_tipo_video)
);

