DROP TABLE YOUTUBE CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS; 
DROP TABLE CANAL CASCADE CONSTRAINTS;
DROP TABLE SHORTS CASCADE CONSTRAINTS;
DROP TABLE VIDEO CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;


CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nomber_usuario VARCHAR2(200) NOT NULL UNIQUE,
    correo VARCHAR2(200) UNIQUE,
    contrasena VARCHAR2(200),
    fecha_de_naciento DATE
);

CREATE TABLE VIDEO(
    id_video NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200),
    fecha_creacion TIMESTAMP,
    duracion_video NUMBER
);

CREATE TABLE CANAL(
    id_canal NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES USUARIO(id_usuario),
    nombre_canal VARCHAR2(200) NOT NULL UNIQUE,
    descripcion VARCHAR2(200),
    id_video NUMBER REFERENCES VIDEO(id_video),
    id_short NUMBER REFERENCES SHORTS(id_short)
);

CREATE TABLE CATEGORIA(
    id_categoria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(200)
);

CREATE TABLE SHORTS(
    id_short NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo_short VARCHAR2(200),
    duracion_short NUMBER NOT NULL,
    descripcion_short VARCHAR2(200)
);

CREATE TABLE YOUTUBE(
    id_usuario NUMBER REFERENCES USUARIO(id_usuario),
    id_categoria NUMBER REFERENCES CATEGORIA(id_categoria),
    id_short NUMBER REFERENCES SHORTS(id_short),
    id_video NUMBER REFERENCES VIDEO(id_video),
    id_canal NUMBER REFERENCES CANAL(id_canal) 
);



COMMIT;

