CREATE TABLE USUARIO(
    ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL, 
    FECHA_NACIMIENTO DATE NOT NULL,
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    EDAD NUMBER(10),
    GENERO VARCHAR2(10),
    CIUDAD VARCHAR2(20),
    TELEFONO VARCHAR2(30),
    MENSAJE VARCHAR2(250)
);


CREATE TABLE CIUDAD(
    ID_CIUDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_CIUDAD VARCHAR2(100) NOT NULL
); 


CREATE TABLE TINDER(
    ID_USUARIO NUMBER,
    ID_LIKE NUMBER,
    ID_NOMBRE NUMBER,
    ID_FOTO NUMBER,
    ID_CIUDAD NUMBER
);


CREATE TABLE FOTO(
    ID_FOTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    URL_FOTO VARCHAR2(250) NOT NULL
);


CREATE TABLE LIKE_USUARIO( 
    ID_LIKE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA_LIKE DATE NOT NULL,
    USUARIO_EMISOR NUMBER NOT NULL,
    USUARIO_RECEPTOR NUMBER NOT NULL
);