DROP TABLE USUARIO;
DROP TABLE CANAL;
DROP TABLE VERMASTARDE;
DROP TABLE LISTAS;
DROP TABLE SUSCRIPTORES;
DROP TABLE COMENTARIOS;
DROP TABLE VIDEOS;
DROP TABLE HISTORIAL;


CREATE TABLE USUARIO(
    id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nick VARCHAR2,
    id_vermastarde NUMBER,
    id_comentarios NUMBER
)

CREATE TABLE LISTAS(
    id_listas NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2
)

CREATE TABLE VERMASTARDE_USUARIO(
    id_listas NUMBER,
    id_usuario NUMBER
)

CREATE TABLE LISTAS_USUARIO(
    id_listas NUMBER,
    id_usuario NUMBER
)

CREATE TABLE SUSCRIPTORES(
    id_usuario NUMBER,
    id_canal NUMBER
)