DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE CANAL CASCADE CONSTRAINTS;
DROP TABLE VIDEO CASCADE CONSTRAINTS;

CREATE TABLE USUARIO(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    correo VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(200),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE CANAL(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER REFERENCES USUARIO(ID),
    nombre_canal VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(250),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE VIDEO(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CANAL NUMBER REFERENCES CANAL(ID),
    titulo VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(250),
    duracion_segundos NUMBER NOT NULL,
    fecha_publicacion TIMESTAMP DEFAULT SYSTIMESTAMP
);


INSERT INTO USUARIO(nombre, correo, password) VALUES ('Gustavo', 'garaneda@gmail.com', 'askdjfhkjdsh87342432587hf8y34987q6ytf94873q59938475');

COMMIT;

SELECT * FROM USUARIO;

INSERT INTO CANAL(ID_USUARIO, nombre_canal, descripcion) VALUES(1, 'Araneda Tutoriales', 'Acá reparamos tecnologia de todo tipo');

COMMIT;

SELECT * FROM USUARIO;

SELECT * FROM CANAL;

SELECT c.NOMBRE_CANAL, c.DESCRIPCION, u.NOMBRE FROM CANAL c
JOIN USUARIO u ON c.ID_USUARIO = u.ID;