DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE CANAL CASCADE CONSTRAINTS;
DROP TABLE VIDEO CASCADE CONSTRAINTS;

CREATE TABLE USUARIO(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    correo VARCHAR2(100),
    contrasenia VARCHAR2(200),
    fecha_creacion DATE
)

CREATE TABLE CANAL(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER REFERENCES USUARIO(ID),
    nombre_Canal VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(250),
    fecha_creacion DATE 
)

CREATE TABLE VIDEO(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CANAL NUMBER REFERENCES CANAL(ID),
    titulo VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(250),
    duracion_segundos NUMBER NOT NULL,
    fecha_publicacion DATE NOT NULL
)

